name: prototype_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs
  - pip
  - pip:
    - pyyaml
    - pyarango
    - uvicorn
    - fastapi
    - spacy
    - pystac-client
    - planetary-computer
    - geojson
    - geocoder
    - parsedatetime
    - sentence-transformers
  
